info:
  namespace: omc_icons
font_images:
  openmc-armor-icon:
    permission: openmc-armor-icon
    show_in_gui: false
    path: "openmc-armor-icon.png"
    scale_ratio: 12
    y_position: 10
  openmc:
    permission: server-icon
    show_in_gui: false
    path: "font/openmc.png"
    scale_ratio: 80
    y_position: 70
  aywenito:
    permission: aywenito
    show_in_gui: true
    path: "font/aywenito.png"
    scale_ratio: 12
    y_position: 9