info:
    namespace: omc_quests
font_images:
    quests_menu:
        permission: confirm.menu
        show_in_gui: true
        suggest_in_command: false
        path: "quests_menu.png"
        y_position: 43