info:
  namespace: omc_company
items:
  10_btn:
    display_name: 10
    resource:
      material: PAPER
      generate: true
      textures:
        - 10_btn

  company_box:
    display_name: "company box"
    resource:
      material: PAPER
      generate: true
      textures:
        - company_box